language: ruby
rvm:
  - 2.1
before_install:
  - gem install bundler -v ‘< 2’
install:
  - bundle install
  - npm install
script:
  - bundle exec jekyll build
#whitelist
branches:
  only:
    - master
after_success: bundle exec s3_website push
